apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    chart: headlamp
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.41.0
    helm:
      releaseName: headlamp
      values: |
        config:
          pluginsDir: /build/plugins
          oidc:
            secret:
              create: false
            externalSecret:
              enabled: true
              name: oidc
        initContainers:
          - command:
              - /bin/sh
              - '-c'
              - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
            image: quay.io/kubescape/headlamp-plugin:v0.10.6
            name: kubescape-plugin
            volumeMounts:
              - mountPath: /build/plugins
                name: headlamp-plugins
        volumeMounts:
          - name: headlamp-plugins
            mountPath: /build/plugins
        volumes:
          - name: headlamp-plugins
            emptyDir: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
